name: ConsoleCommandBlocker
version: '1.0-SNAPSHOT'
main: com.example.consolecommandblocker.ConsoleCommandBlocker
api-version: '1.16'
description: Блокирует выполнение команд из консоли сервера

permissions:
  consoleblocker.bypass:
    description: Позволяет обходить блокировку команд в консоли
    default: op
